/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("lsmtree.java-application-conventions")
}

dependencies {
    implementation("org.springframework:spring-context:6.2.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.16.1")
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")
}

application {
    // Define the main class for the application.
    mainClass.set("com.org.gangmin.LsmTree")
}
