/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("lsmtree.java-application-conventions")
}

dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("com.org.gangmin.LsmTree")
}
